site_name: One Last Kiss
site_dir: 'site'
site_url: https://localhost:8000/

repo_name: aletolia/aletolia.github.io # ä»“åº“åç§°
repo_url: https://github.com/aletolia/aletolia.github.io.git # ä»“åº“åœ°å€

theme:
  # logo: assets\saber.ico
  favicon: img/favicon.ico
  logo: img/icon.png
  name: material
  custom_dir: docs/assets
  features:
    - announce.dismiss # å¯ä»¥å‰æ‰å…¬å‘Šçš„åŠŸèƒ½
    - content.action.edit # ç¼–è¾‘æŒ‰é’®ï¼Œä¼¼ä¹æ²¡å•¥ç”¨
    - content.action.view # æŸ¥çœ‹æŒ‰é’®ï¼Œä¼¼ä¹æ²¡å•¥ç”¨
    - content.code.annotate # ä»£ç æ³¨é‡Šï¼Œå…·ä½“ä¸æ¸…æ¥š
    - content.code.copy # å¤åˆ¶ä»£ç æŒ‰é’®
    - content.code.select # é€‰æ‹©ä»£ç æŒ‰é’®
    # - content.tabs.link # é“¾æ¥æ ‡ç­¾
    - content.tooltips # ä¸å¤ªæ¸…æ¥šå‘¢è¿™ä¸ª
    # - header.autohide # è‡ªåŠ¨éšè—header
    - navigation.expand # é»˜è®¤å±•å¼€å¯¼èˆªæ 
    - navigation.footer # åº•éƒ¨å¯¼èˆªæ 
    - navigation.indexes # ç´¢å¼•æŒ‰é’®å¯ä»¥ç›´æ¥è§¦å‘æ–‡ä»¶ï¼Œè€Œä¸æ˜¯åªèƒ½ç‚¹å‡»å…¶ä¸‹å±é€‰é¡¹æµè§ˆï¼Œè¿™ä¸ªåŠŸèƒ½å¯ä»¥ç»™å¯¹åº”çš„sectionæä¾›å¾ˆå¥½çš„é¢„è§ˆå’Œå¯¼èˆªåŠŸèƒ½
    # - navigation.instant # ç¬é—´åŠ è½½ æœ€å¥½æ³¨é‡Šæ‰ï¼Œå¤šè¯­è¨€åˆ‡æ¢è¿™ä¸ªä¼šå¯¼è‡´è·³å›é¦–é¡µ
    - navigation.instant.prefetch # é¢„åŠ è½½
    - navigation.instant.progress # è¿›åº¦æ¡
    - navigation.path # å¯¼èˆªè·¯å¾„ï¼Œ ç›®å‰å¥½åƒæ²¡å•¥ç”¨
    # - navigation.prune # åªæ„å»ºå¯è§çš„é¡µé¢
    - navigation.sections # å¯¼èˆªæ çš„section
    - navigation.tabs # é¡¶çº§ç´¢å¼•è¢«ä½œä¸ºtab
    - navigation.tabs.sticky # tabå§‹ç»ˆå¯è§
    - navigation.top # å¼€å¯é¡¶éƒ¨å¯¼èˆªæ 
    - navigation.tracking # å¯¼èˆªæ è·Ÿè¸ª
    - search.highlight # æœç´¢é«˜äº®
    - search.share # æœç´¢åˆ†äº«
    - search.suggest # æœç´¢å»ºè®®
    - toc.follow # ç›®å½•è·Ÿè¸ª-é¡µé¢å³ä¾§çš„å°ç›®å½•
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - ğŸ  Home: 
    - index.md
  - â›ï¸ CV and Multimodels:
    - Mygo.md
    - DINO.md
    - Mamba.md
    - ViT.md
    - Self-Supervised Learning MoCo.md
    - Self-Supervised Learning MoCoV2,3.md
    - Vision Transformer (ä¸€).md
    - Vision Transformer  (äºŒ).md
    - Vision Transformer (ä¸‰).md
    - Vision Transformer (å››) (TNT).md
    - Vision Transformer (çŸ¥è¯†è’¸é¦ é¢„è®­ç»ƒï¼‰.md
    - Vision Transformer (PyramidTNT).md
    - å‚…é‡Œå¶çº§æ•°å’Œå‚…é‡Œå¶å˜æ¢ä¸“é¢˜.md
    - Python å­˜å‚¨ä¸è¯»å– HDF5 æ–‡ä»¶.md
    - Segment Anything in Medical Images.md
    - Vision Mamba Efficient Visual Representation Learning with Bidirectional State Space Model.md
    
    - ğŸš‘ åŒ»å­¦å½±åƒç›¸å…³:
      - Why is the winner the best.md
      - PORPOISE.md
      - HIPT.md
      - Data-efficient and weakly supervised computational pathology on whole-slide images(CLAM).md
      - Towards a general-purpose foundation model for computational pathology.md
      - A whole-slide foundation model for digital pathology from real-world data.md
      - A visual-language foundation model for computational pathology.md
      - Recurrent memory with optimal polynomial projections..md
      - Modeling Dense Multimodal Interactions Between Biological Pathways and Histology for Survival Prediction.md
      - Inferring super-resolution tissue architecture by integrating spatial transcriptomics with histology.md
      - Prediction of recurrence risk in endometrial cancer with multimodal deep learning.md

  - ğŸš€ Re:0 Road to CPath & Visualization:
    - Session 1.ipynb
    - Session 2.ipynb
    - Session 3.ipynb
    - How to visualize Attention.md
    - AttentionViz A Global View of Transformer Attention.md
    - Transformer Interpretability Beyond Attention Visualization.md
    - Visualization Work Flow.md
    - Attention Generation Work Flow.md
    - ğŸª› PyTorch:
      - Autograd mechanics â€” PyTorch 2_3 documentation.md
      - PyTorch Autograd Explained - In-depth Tutorial.md

  - ğŸ’¤ Re:0 Road to scRNA-seq Analysis:

    - Using Python:
      - â³ CHAPTER 1 ç®€ä»‹:
        - 1.1 Single-cell RNA sequencing.md
        - 1.2 Raw Data Processing.md
        - 1.3 Analysis frameworks and tools.md
      - ğŸŒ CHAPTER 2 æ•°æ®å‡†å¤‡ä¸å¯è§†åŒ–:
        - 2.1 quality_control.ipynb
        - 2.2 normalization.ipynb
        - 2.3_feature_selection.ipynb
        - 2.4_dimensionality_reduction.ipynb
      - ğŸ€ CHAPTER 3 è¯†åˆ«ç»†èƒç»“æ„:
        - 3.1clustering.ipynb
        - 3.2annotation.ipynb
        - 3.3integration.ipynb
      - â±ï¸ CHAPTER 4 æ¨æ–­ç»†èƒè½¨è¿¹:
        - pseudotemporal.ipynb
        - rna_velocity.ipynb
        - lineage_tracing.ipynb
      - ğŸ CHAPTER 5 åº”å¯¹ç‰¹æ®Šæƒ…å†µ:
        - differential_gene_expression.ipynb
        - compositional.ipynb
        - gsea_pathway.ipynb
        - perturbation_modeling.ipynb
      - âš™ï¸ CHAPTER 6 æœºåˆ¶å»ºæ¨¡:
        - gene_regulatory_networks.ipynb
        - cell_cell_communication.ipynb
      - ğŸ”“ CHAPTER 7 åå·ç§¯:
        - bulk_deconvolution.ipynb
    - ç®€æ˜æ˜“æ‡‚çš„å•ç»†èƒåˆ†ææµç¨‹ï¼ˆä½¿ç”¨ R è¯­è¨€ï¼‰:
        - å‰è¨€.md
        - ç¯å¢ƒé…ç½®.md
        - 1.1 æ„å»ºå•ç»†èƒ RNA-seq åˆ†æç¯å¢ƒ.md
        - 1.2 R ç¯å¢ƒå®‰è£….md
        - 1.3 Docker å®‰è£….md
        - 1.4 åœ¨ Docker ä¸­å¯åŠ¨ Rstudio.md
        - 1.5 æœ‰å…³ Bioconductor.md
        - 2.1 R çš„åŸºæœ¬ç”¨æ³•.md
        - 2.2 å¦‚ä½•å¤„ç† DataFrameï¼Ÿ.md
        - 2.3 ä½¿ç”¨ ggplot2 å¯è§†åŒ–æ•°æ®.md
        - 3.1 PCA.md
        - 3.2 ä½¿ç”¨ clusterPlofiler è¿›è¡Œå¯Œé›†åˆ†æ.md
        - 3.3 åŸºå› æœ¬ä½“ï¼ˆGOï¼‰ä¸­å„ BPã€MF å’Œ CC çš„å¯Œé›†åˆ†æ.md
        - 3.3 ä½¿ç”¨ DEseq2 æå– RNA-seq åˆ†ææ•°æ®ä¸­çš„ DEG.md
        - 3.4 ä½¿ç”¨å…¶ä»–æ•°æ®åº“ï¼ˆKEGGã€Reactome ç­‰ï¼‰è¿›è¡Œå¯Œé›†åˆ†æ.md
        - 4.1 scRNA-seq æ¦‚è¦.md
        - 4.2 å‡†å¤‡ä½¿ç”¨ Seurat è¿›è¡Œåˆ†æ.md
        - 4.3 ä½¿ç”¨ Seurat è¿›è¡Œæ•°æ®é¢„å¤„ç†.md
        - 4.4 ä½¿ç”¨ Seurat è¿›è¡Œæ•°æ®åˆ†æçš„ä¸€èˆ¬é¡ºåº.md
        - 5.1 å¦‚ä½•æŸ¥æ‰¾å•ç»†èƒ RNA-seq æ•°æ®.md
        - 5.2 ä¸ºæ¯ä¸ªç°‡è‡ªåŠ¨æ·»åŠ ç»†èƒæ³¨é‡Šæ ‡ç­¾.md
        - 5.3 ä½¿ç”¨ FeaturePlot æ£€æŸ¥åŸºå› è¡¨è¾¾.md
        - 5.4 å°†å•ç»†èƒ RNA-seq æ•°æ®é›†ç›¸äº’ç»“åˆ.md
        - 5.5 çº æ­£æ‰¹æ¬¡æ•ˆåº”ï¼Œæ¯”è¾ƒå¯¹ç…§ç»„å’Œåˆºæ¿€ç»„.md
        - 5.6 ç¡®å®šæ¯ä¸ªç¾¤ç»„çš„æ ‡è®°åŸºå› .md
        - 6.1 å¦‚ä½•ä½¿ç”¨ Cell Ranger ç»Ÿè®¡ scRNA-seq æ•°æ®ä¸­çš„åŸºå› è¡¨è¾¾æ°´å¹³.md
        - 6.2 ä½¿ç”¨ Cell Ranger å¤„ç† NCBI Sequence Read Archive (SRA) æ•°æ®.md
        - 7.1 å…³äº scRNA-seq æ•°æ®çš„è´¨é‡æ§åˆ¶.md
        - 7.2 ä½¿ç”¨ DoubleFinder æ£€æµ‹åŒé‡ç»†èƒ.md
        - 7.3 ç”¨ CellBender å»é™¤èƒŒæ™¯ RNA.md

  - ğŸ§¬ scRNA Analysis:

    - ğŸ Using Python:
      - Large-scale foundation model on single-cell transcriptomics.md
      - scGPT toward building a foundation model for single-cell multi-omics using generative AI.md
      - scBERT as a large-scale pretrained deep language model for cell type annotation of single-cell RNA-seq data.md
      - RNA velocity of single cells.md
      - TFvelo_gene regulation inspired RNA velocity estimation.md
      - Disentanglement of single-cell data with biolord.md
      - â­â­â­C5aR1 inhibition reprograms tumor associated macrophages and reverses PARP inhibitor resistance in breast cancer.md
      - Spatial transition tensor of single cells.md
      - Statistical method scDEED for detecting dubious 2D single-cell embeddings and optimizing t-SNE and UMAP hyperparameters.md
      - scRank infers drug-responsive cell types from untreated scRNA-seq data using a target-perturbed gene regulatory network.md
    - ğŸ“” æ–‡çŒ®:
      - scRNA-seq of gastric tumor shows complex intercellular interaction with an alternative T cell exhaustion trajectoryï¼ˆå‚è€ƒï¼‰.md
      - Single-cell analysis reveals new evolutionary complexity in uveal melanomaï¼ˆå‚è€ƒ 2ï¼‰.md
      - Single-cell characterization of macrophages in uveal melanoma uncovers transcriptionally heterogeneous subsets conferring poor prognosis and aggressive behaviorï¼ˆèŒƒä¾‹ 1ï¼‰.md
      - ScRNA-seq of gastric cancer tissues reveals differences in the immune microenvironment of primary tumors and metastases.md
      - Blimp-1 and c-Maf regulate immune gene networks to protect against distinct pathways of pathobiont-induced colitis.md
      - Single cell analysis unveils B cell-dominated immune subtypes in HNSCC for enhanced prognostic and therapeutic stratification.md
      - Single-cell spatial multi-omics and deep learning dissect enhancer-driven gene regulatory networks in liver zonation.md
      - Neutrophil profiling illuminates anti-tumor antigen presenting potency.md
      - A blueprint for tumor-infiltrating B cells across human cancers.md
      - Single-cell transcriptomic analyses reveal distinct immune cell contributions to epithelial barrier dysfunction in checkpoint inhibitor colitis.md
      - Systematic dissection of tumor-normal single-cell ecosystems across a thousand tumors of 30 cancer types.md
      - The aged tumor microenvironment limits T cell control of cancer.md
      - TIM-3+ CD8 T cells with a terminally exhausted phenotype retain functional capacity in hematological malignancies.md
      - A lactate-SREBP2 signaling axis drives tolerogenic dendritic cell maturation and promotes cancer progression.md
      - A human omentum-specific mesothelial-like stromal population inhibits adipogenesis through IGFBP2 secretion.md
      - Interferon-stimulated neutrophils as a predictor of immunotherapy response.md
      - Repression of latent NF-ÎºB enhancers by PDX1 regulates Î² cell functional heterogeneity.md
      - A systematic pan-cancer study on deep learning-based prediction of multi-omic biomarkers from routine pathology images.md
      - Single-cell and spatial transcriptomics analysis of non-small cell lung cancer.md
      - Seeing data as t-SNE and UMAP do.md      
      - Mapping the cellular biogeography of human bone marrow niches using single-cell transcriptomics and proteomic imaging.md
      - Onco-fetal Reprogramming of Endothelial Cells Drives Immunosuppressive Macrophages in Hepatocellular Carcinoma.md
      - Single-cell analysis of anti-BCMA CAR T cell therapy in patients with central nervous system autoimmunity.md
      - Single-cell sequencing depicts tumor architecture and empowers clinical decision in metastatic conjunctival melanoma.md
      - PR-SET7 epigenetically restrains uterine interferon response and cell death governing proper postnatal stromal development.md
      - Clonal associations between lymphocyte subsets and functional states in rheumatoid arthritis synovium.md

  - ğŸ“ Data Structures:
    - ç¬¬ 1 ç«  python å…¥é—¨.md
    - ç¬¬ 2 ç«  é¢å‘å¯¹è±¡ç¼–ç¨‹.md
    - ç¬¬ 3 ç«  ç®—æ³•åˆ†æ.md
    - ç¬¬ 4 ç«  é€’å½’.md
    - ç¬¬ 5 ç«  åŸºäºæ•°ç»„çš„åºåˆ—.md
    - ç¬¬ 6 ç«  æ ˆã€é˜Ÿåˆ—å’ŒåŒç«¯é˜Ÿåˆ—.md
    - ç¬¬ 7 ç«  é“¾è¡¨(Linked Lists).md
    - ç¬¬ 8 ç«  æ ‘ â˜….md
    - ç¬¬ 9 ç«  ä¼˜å…ˆçº§é˜Ÿåˆ—.md

  - ğŸ’¡ Reviews:
    - ğŸ§­ scRNA analysis:
      - Best practices for single-cell analysis across modalities.md
      - Multi-omics integration in biomedical research â€“ A metabolomics-centric review.md
      - Museum of spatial transcriptomics.md
      - A guide to artificial intelligence for cancer researchers.md
    - ğŸ¦  Metabolism:
      - Metabolic analysis as a driver for discovery, diagnosis, and therapy.md
      - Metabolic heterogeneity in cancer.md
      - Toward modeling metabolic state from single-cell transcriptomics.md
      - Metabolic reprogramming and cancer progression.md
    - Protein:
      - Proteomic and interactomic insights into the molecular basis of cell functional diversity.md


extra:
  analytics:
    provider: google
    property: G-M0R7V8QGQ7

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.keys # æŒ‰é”®é«˜äº®ï¼Œç±»ä¼¼äºè¡Œå†…ä»£ç é‚£ç§ï¼Œå¦‚ <kbd>Ctrl</kbd>ï¼Œæˆ–è€…å¸¦å›¾æ ‡çš„æ ¼å¼ï¼ˆå¼ºåˆ¶å°å†™ï¼‰++ctrl++ï¼Œä¹Ÿå¯ç»„åˆ ++ctrl+s++ï¼ˆæ¨èç¬¬äºŒç§æ–¹å¼ï¼Œç¬¬äºŒç§è‡ªå¸¦å›¾æ ‡ï¼‰
  - pymdownx.mark # å…è®¸æ–‡æœ¬ä¸‹åˆ’çº¿ï¼Œå³ ^^Text^^
  - pymdownx.caret # å…è®¸æ–‡æœ¬é«˜äº®ï¼Œå³ ==Text==
  - pymdownx.tilde
  - pymdownx.tasklist: # å…è®¸ Todo åˆ—è¡¨æ¸…å•
      custom_checkbox: true # å…è®¸ä¿®æ”¹å…¶æ ·å¼ï¼Œä¸ç„¶ç”¨é»˜è®¤æ ·å¼å°±å¾ˆä¸‘
      clickable_checkbox: true # æ˜¯å¦å¯é€šè¿‡ç‚¹å‡»åˆ‡æ¢çŠ¶æ€ï¼ˆä½†æ— å®é™…æ›´æ”¹ï¼Œåªæœ‰è§†è§‰æ•ˆæœï¼‰

plugins: 
  - mkdocs-jupyter
  - search
  # - statistics: # æ•°æ®ç»Ÿè®¡æ’ä»¶ï¼ˆpip install mkdocs-statistics-pluginï¼‰
  #     codelines_per_minute: 15 # æ¯åˆ†é’Ÿå¯çœ‹çš„ä»£ç è¡Œæ•°
  #     words_per_minute: 150 # æ¯åˆ†é’Ÿå¯çœ‹çš„æ–‡æœ¬æ•°



# ä¸‹é¢æ˜¯æç¤ºå—è¯­æ³•
# !!! note "å¯ä»¥åŒå¼•å·ä¸­æŒ‡æ˜æ ‡é¢˜"
#     éšä¾¿å¤šå°‘ç¼©è¿›æ–‡æœ¬.

#     ç©ºè¡Œåˆ†æ®µ.
# !!! hint
#     æ ‡é¢˜ä¼šè‡ªåŠ¨å¤§å†™ã€‚
# !!! important ""
#     æ— æ ‡é¢˜æç¤ºå—ã€‚
# !!! danger highlight blink "ä¸è¦åœ¨å®¶é‡Œåš"
#     ...

# mkdocs.yml file

# other settings ...



# other settings ...

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - extra.js  
  - js/toggle_sidebar.js
  # - https://cdn.jsdelivr.net/npm/canvas-nest.js/dist/canvas-nest.js

extra_css: 
  - extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
# other settings ...
# Hello World




