site_name: One Last Kiss
site_dir: 'site'
site_url: https://localhost:8000/

repo_name: aletolia/aletolia.github.io # 仓库名称
repo_url: https://github.com/aletolia/aletolia.github.io.git # 仓库地址

theme:
  # logo: assets\saber.ico
  favicon: img/favicon.ico
  logo: img/icon.png
  name: material
  custom_dir: custom
  features:
    - announce.dismiss # 可以叉掉公告的功能
    - content.action.edit # 编辑按钮，似乎没啥用
    - content.action.view # 查看按钮，似乎没啥用
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    # - content.code.select # 选择代码按钮
    # - content.tabs.link # 链接标签
    - content.tooltips # 不太清楚呢这个
    # - header.autohide # 自动隐藏header
    - navigation.expand # 默认展开导航栏
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    # - navigation.instant # 瞬间加载 最好注释掉，多语言切换这个会导致跳回首页
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径， 目前好像没啥用
    # - navigation.prune # 只构建可见的页面
    - navigation.sections # 导航栏的section
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: 
    - index.md
  - CV and Multimodels:
    - Mygo.md
    - Segment Anything in Medical Images.md
    - Vision Mamba Efficient Visual Representation Learning with Bidirectional State Space Model.md
    - DINO.md
    - Self-Supervised Learning MoCo.md
    - Self-Supervised Learning MoCoV2,3.md
    - ViT.md
    - Vision Transformer (一).md
    - Vision Transformer  (二).md
    - Vision Transformer (三).md
    - Vision Transformer (四) (TNT).md
    - Vision Transformer (知识蒸馏 预训练）.md
    - Vision Transformer (PyramidTNT).md
    - 傅里叶级数和傅里叶变换专题.md
    
    - 医学影像相关:
      - PORPOISE.md
      - HIPT.md
      - Data-efficient and weakly supervised computational pathology on whole-slide images(CLAM).md
    - Recurrent memory with optimal polynomial projections..md

  - scRNA Analysis:
    - Using Python:
      - scGPT toward building a foundation model for single-cell multi-omics using generative AI.md
      - scBERT as a large-scale pretrained deep language model for cell type annotation of single-cell RNA-seq data.md
      - RNA velocity of single cells.md
    - 文献:
      - scRNA-seq of gastric tumor shows complex intercellular interaction with an alternative T cell exhaustion trajectory（参考）.md
      - Single-cell analysis reveals new evolutionary complexity in uveal melanoma（参考 2）.md
      - Single-cell characterization of macrophages in uveal melanoma uncovers transcriptionally heterogeneous subsets conferring poor prognosis and aggressive behavior（范例 1）.md
      - ScRNA-seq of gastric cancer tissues reveals differences in the immune microenvironment of primary tumors and metastases.md

  - Data Structures:
    - 第 1 章 python 入门.md
    - 第 2 章 面向对象编程.md
    - 第 3 章 算法分析.md
    - 第 4 章 递归.md
    - 第 5 章 基于数组的序列.md
    - 第 6 章 栈、队列和双端队列.md
    - 第 7 章 链表(Linked Lists).md
    - 第 8 章 树 ★.md
    - 第 9 章 优先级队列.md

# plugins:
#   - social
#   - search

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.arithmatex



# 下面是提示块语法
# !!! note "可以双引号中指明标题"
#     随便多少缩进文本.

#     空行分段.
# !!! hint
#     标题会自动大写。
# !!! important ""
#     无标题提示块。
# !!! danger highlight blink "不要在家里做"
#     ...

# mkdocs.yml file

# other settings ...



# other settings ...

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - extra.js  
  - js/toggle_sidebar.js
  # - https://cdn.jsdelivr.net/npm/canvas-nest.js/dist/canvas-nest.js

extra_css: 
  - extra.css

# other settings ...


