site_name: One Last Kiss
site_dir: 'site'
site_url: https://localhost:8000/

repo_name: aletolia/aletolia.github.io # ä»“åº“åç§°
repo_url: https://github.com/aletolia/aletolia.github.io.git # ä»“åº“åœ°å€

theme:
  # logo: assets\saber.ico
  favicon: img/favicon.ico
  logo: img/icon.png
  name: material
  custom_dir: docs/assets
  features:
    - announce.dismiss # å¯ä»¥å‰æ‰å…¬å‘Šçš„åŠŸèƒ½
    - content.action.edit # ç¼–è¾‘æŒ‰é’®ï¼Œä¼¼ä¹æ²¡å•¥ç”¨
    - content.action.view # æŸ¥çœ‹æŒ‰é’®ï¼Œä¼¼ä¹æ²¡å•¥ç”¨
    - content.code.annotate # ä»£ç æ³¨é‡Šï¼Œå…·ä½“ä¸æ¸…æ¥š
    - content.code.copy # å¤åˆ¶ä»£ç æŒ‰é’®
    - content.code.select # é€‰æ‹©ä»£ç æŒ‰é’®
    # - content.tabs.link # é“¾æ¥æ ‡ç­¾
    - content.tooltips # ä¸å¤ªæ¸…æ¥šå‘¢è¿™ä¸ª
    # - header.autohide # è‡ªåŠ¨éšè—header
    - navigation.expand # é»˜è®¤å±•å¼€å¯¼èˆªæ 
    - navigation.footer # åº•éƒ¨å¯¼èˆªæ 
    - navigation.indexes # ç´¢å¼•æŒ‰é’®å¯ä»¥ç›´æ¥è§¦å‘æ–‡ä»¶ï¼Œè€Œä¸æ˜¯åªèƒ½ç‚¹å‡»å…¶ä¸‹å±é€‰é¡¹æµè§ˆï¼Œè¿™ä¸ªåŠŸèƒ½å¯ä»¥ç»™å¯¹åº”çš„sectionæä¾›å¾ˆå¥½çš„é¢„è§ˆå’Œå¯¼èˆªåŠŸèƒ½
    # - navigation.instant # ç¬é—´åŠ è½½ æœ€å¥½æ³¨é‡Šæ‰ï¼Œå¤šè¯­è¨€åˆ‡æ¢è¿™ä¸ªä¼šå¯¼è‡´è·³å›é¦–é¡µ
    - navigation.instant.prefetch # é¢„åŠ è½½
    - navigation.instant.progress # è¿›åº¦æ¡
    - navigation.path # å¯¼èˆªè·¯å¾„ï¼Œ ç›®å‰å¥½åƒæ²¡å•¥ç”¨
    # - navigation.prune # åªæ„å»ºå¯è§çš„é¡µé¢
    - navigation.sections # å¯¼èˆªæ çš„section
    - navigation.tabs # é¡¶çº§ç´¢å¼•è¢«ä½œä¸ºtab
    - navigation.tabs.sticky # tabå§‹ç»ˆå¯è§
    - navigation.top # å¼€å¯é¡¶éƒ¨å¯¼èˆªæ 
    - navigation.tracking # å¯¼èˆªæ è·Ÿè¸ª
    - search.highlight # æœç´¢é«˜äº®
    - search.share # æœç´¢åˆ†äº«
    - search.suggest # æœç´¢å»ºè®®
    - toc.follow # ç›®å½•è·Ÿè¸ª-é¡µé¢å³ä¾§çš„å°ç›®å½•
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - ğŸ  Home: 

  
    - index.md
  - â›ï¸ CV and Multimodels:
    - Mygo.md
    - Segment Anything in Medical Images.md
    - Vision Mamba Efficient Visual Representation Learning with Bidirectional State Space Model.md
    - DINO.md
    - Self-Supervised Learning MoCo.md
    - Self-Supervised Learning MoCoV2,3.md
    - ViT.md
    - Vision Transformer (ä¸€).md
    - Vision Transformer  (äºŒ).md
    - Vision Transformer (ä¸‰).md
    - Vision Transformer (å››) (TNT).md
    - Vision Transformer (çŸ¥è¯†è’¸é¦ é¢„è®­ç»ƒï¼‰.md
    - Vision Transformer (PyramidTNT).md
    - å‚…é‡Œå¶çº§æ•°å’Œå‚…é‡Œå¶å˜æ¢ä¸“é¢˜.md
    - Python å­˜å‚¨ä¸è¯»å– HDF5 æ–‡ä»¶.md
    
    - ğŸš‘ åŒ»å­¦å½±åƒç›¸å…³:
      - PORPOISE.md
      - HIPT.md
      - Data-efficient and weakly supervised computational pathology on whole-slide images(CLAM).md
      - Towards a general-purpose foundation model for computational pathology.md
      - A visual-language foundation model for computational pathology.md
      - Recurrent memory with optimal polynomial projections..md
      - Modeling Dense Multimodal Interactions Between Biological Pathways and Histology for Survival Prediction.md

  - ğŸš€ Re:0 Road to CPath & Visualization:
    - Session 1.ipynb
    - Session 2.ipynb
    - Session 3.ipynb
    - How to visualize Attention.md
    - AttentionViz A Global View of Transformer Attention.md
    - Transformer Interpretability Beyond Attention Visualization.md
    - Visualization Work Flow.md
    - Attention Generation Work Flow.md
    - ğŸª› PyTorch:
      - Autograd mechanics â€” PyTorch 2_3 documentation.md
      - docs\PyTorch Autograd Explained - In-depth Tutorial.md
      

  - ğŸ§¬ scRNA Analysis:
    - ğŸ Using Python:
      - scGPT toward building a foundation model for single-cell multi-omics using generative AI.md
      - scBERT as a large-scale pretrained deep language model for cell type annotation of single-cell RNA-seq data.md
      - RNA velocity of single cells.md
      - TFvelo_gene regulation inspired RNA velocity estimation.md
    - ğŸ“” æ–‡çŒ®:
      - scRNA-seq of gastric tumor shows complex intercellular interaction with an alternative T cell exhaustion trajectoryï¼ˆå‚è€ƒï¼‰.md
      - Single-cell analysis reveals new evolutionary complexity in uveal melanomaï¼ˆå‚è€ƒ 2ï¼‰.md
      - Single-cell characterization of macrophages in uveal melanoma uncovers transcriptionally heterogeneous subsets conferring poor prognosis and aggressive behaviorï¼ˆèŒƒä¾‹ 1ï¼‰.md
      - ScRNA-seq of gastric cancer tissues reveals differences in the immune microenvironment of primary tumors and metastases.md
      - Blimp-1 and c-Maf regulate immune gene networks to protect against distinct pathways of pathobiont-induced colitis.md
      - Single cell analysis unveils B cell-dominated immune subtypes in HNSCC for enhanced prognostic and therapeutic stratification.md
      - Single-cell spatial multi-omics and deep learning dissect enhancer-driven gene regulatory networks in liver zonation.md

  - ğŸ“ Data Structures:
    - ç¬¬ 1 ç«  python å…¥é—¨.md
    - ç¬¬ 2 ç«  é¢å‘å¯¹è±¡ç¼–ç¨‹.md
    - ç¬¬ 3 ç«  ç®—æ³•åˆ†æ.md
    - ç¬¬ 4 ç«  é€’å½’.md
    - ç¬¬ 5 ç«  åŸºäºæ•°ç»„çš„åºåˆ—.md
    - ç¬¬ 6 ç«  æ ˆã€é˜Ÿåˆ—å’ŒåŒç«¯é˜Ÿåˆ—.md
    - ç¬¬ 7 ç«  é“¾è¡¨(Linked Lists).md
    - ç¬¬ 8 ç«  æ ‘ â˜….md
    - ç¬¬ 9 ç«  ä¼˜å…ˆçº§é˜Ÿåˆ—.md


# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.arithmatex

plugins: 
  - mkdocs-jupyter
  - search




# ä¸‹é¢æ˜¯æç¤ºå—è¯­æ³•
# !!! note "å¯ä»¥åŒå¼•å·ä¸­æŒ‡æ˜æ ‡é¢˜"
#     éšä¾¿å¤šå°‘ç¼©è¿›æ–‡æœ¬.

#     ç©ºè¡Œåˆ†æ®µ.
# !!! hint
#     æ ‡é¢˜ä¼šè‡ªåŠ¨å¤§å†™ã€‚
# !!! important ""
#     æ— æ ‡é¢˜æç¤ºå—ã€‚
# !!! danger highlight blink "ä¸è¦åœ¨å®¶é‡Œåš"
#     ...

# mkdocs.yml file

# other settings ...



# other settings ...

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - extra.js  
  - js/toggle_sidebar.js
  # - https://cdn.jsdelivr.net/npm/canvas-nest.js/dist/canvas-nest.js

extra_css: 
  - extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
# other settings ...
# Hello World


